image:
  name:    "madlad-custom-patrick"

build:
  mg5:     "/home/pdougan/EventGeneration/MG5_aMC_v3_5_4"
  pythia:  "8.301"
  lhapdf:  "6.5.0"
  fastjet: "3.4.0"
  delphes: "3.5.0"

extra:
  pdfs:   [260000, 260400, 303400]          # Additional pdf sets
  # models: ["QCKM_5_Aug21v2", "UFO", "UFO_OE", "YqHEFT_UFO"]  # Additional models